In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(type(a))
print(a)
b = np.array([[1,2,3],[4,5,6]], dtype=bool)
print(b)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[[ True  True  True]
 [ True  True  True]]


In [9]:
np.arange(1,11,2)
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.random.random((3,4))

array([[0.0338866 , 0.25793155, 0.87122924, 0.38878455],
       [0.02474931, 0.12043188, 0.44239711, 0.26698375],
       [0.4543821 , 0.91471479, 0.67359437, 0.4908673 ]])

In [11]:
# creates 10 equidistant  points between two points
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
a2 = np.arange(16).reshape(2,2,2,2)
#a2 = np.arange(16).reshape(4,4)

a2.ndim   # 4
a2.shape   # (2,2,2,2)
a2.size    # 16
a2.itemsize    # per item size
a2.dtype     # dtype('int32')

dtype('int32')

In [44]:
a = np.arange(10)
print(a.dtype)

a3 = a.astype(np.int16)
print(a3.dtype)

int32
int16


In [45]:
b1 = np.arange(12).reshape(3,4)
b2 = np.arange(12,24).reshape(3,4)
print(b1)
print(b2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [53]:
#scalar operations
print(b1*2)
print(b1+2)
print(b1**2)

# vector operations
print(b1*b2)
print(b1-b2)
print(b1+b2)
print(b1/b2)
print(b1**b2)

# relational operations
print(b1>b2)


[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[          0           1       16384    14348907]
 [          0 -1564725563  1159987200   442181591]
 [          0  1914644777 -1304428544  -122979837]]


In [65]:
#numpy functions

c1 = np.random.random((3,3))
#c1 = c1.astype(dtype=np.int32)
print(c1)
c1 = np.round(c1*100)
print(c1)
c1.dtype

[[0.82942959 0.31830101 0.94955421]
 [0.34783464 0.48634133 0.66918854]
 [0.13957663 0.16262937 0.68563659]]
[[83. 32. 95.]
 [35. 49. 67.]
 [14. 16. 69.]]


dtype('float64')

In [74]:
print(np.max(c1))

# 0 -> col 1 -> row
print(np.max(c1,axis=0))
print(np.max(c1,axis=1))

print(np.min(c1))
print(np.sum(c1))
print(np.prod(c1))
print(np.mean(c1))
print(np.median(c1))
print(np.std(c1))
print(np.var(c1))


95.0
[83. 49. 95.]
[95. 67. 69.]
14.0
460.0
448113174297600.0
51.111111111111114
49.0
27.39604369022183
750.5432098765433


In [77]:
c2 = np.arange(12).reshape(3,4)
c3 = np.arange(12,24).reshape(4,3)
print(c2)
print(c3)
np.dot(c2,c3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [78]:
np.exp(a1)

array([[[[1.00000000e+00, 2.71828183e+00],
         [7.38905610e+00, 2.00855369e+01]],

        [[5.45981500e+01, 1.48413159e+02],
         [4.03428793e+02, 1.09663316e+03]]],


       [[[2.98095799e+03, 8.10308393e+03],
         [2.20264658e+04, 5.98741417e+04]],

        [[1.62754791e+05, 4.42413392e+05],
         [1.20260428e+06, 3.26901737e+06]]]])

In [85]:
d1 = np.random.random((2,3))*100
print(d1)
print(np.round(d1))
print(np.floor(d1))
print(np.ceil(d1))


[[83.43627729 68.31751294 28.45524315]
 [94.43937252 57.91824514 36.4365435 ]]
[[83. 68. 28.]
 [94. 58. 36.]]
[[83. 68. 28.]
 [94. 57. 36.]]
[[84. 69. 29.]
 [95. 58. 37.]]


In [94]:
# indexing
print(d1[1,0])
print(d1[1][0])


d2 = np.arange(27).reshape(3,3,3)
print(d2)
print(d2[2,0,2])

94.43937252284782
94.43937252284782
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
20


In [145]:
#slicing
e1 = np.arange(10)
print(e1)
print(e1[2:7])
print(e1[2:7:2])


e2 = np.arange(12).reshape(3,4)
print(e2)
print(e2[0,:])
print(e2[:,2])
print(e2[1:3, 1:3])
print(e2[1:, 1:3])

print(e2[::2,::3])
print(e2[::2,1::2])

e3 = np.arange(27).reshape(3,3,3)
print(e3)
print(e3[1])
print(e3[0, 1,:])
print(e3[2,1:,1:])


[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[3 4 5]
[[22 23]
 [25 26]]


In [144]:
print(e3[0,0,::2], e3[2,0,::2])

# 2 jumps in column, need first row and then two jumps again
print(e3[::2,0,::2])

[0 2] [18 20]
[[ 0  2]
 [18 20]]


In [147]:
for i in e3:
    print(i)
    
# converts into 1d array and then returns
for i in np.nditer(e3):
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [152]:
print(e3)

# below are both transpose
e4 = np.transpose(e3)
print(e4)
print(e3.T)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
________________
[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]
________________
[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


In [153]:
#ravel  (gives it as 1d array)
e5 = e3.ravel()
print(e5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [156]:
# horizontal stacking
f1 = np.arange(12).reshape(3,4)
f2 = np.arange(12,24).reshape(3,4)

f3 = np.hstack((f1,f2))
print(f3)

# vertical stacking
f4 = np.vstack((f1,f2))
print(f4)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [160]:
# horizontal splitting
# has to be equal division
f5 = np.hsplit(f4,2)
print(f5)

# vertical splitting
f6 = np.vsplit(f4,2)
print(f6)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]
