In [10]:
# single dimensional
import numpy as np
a = np.random.randint(1,100,15)
print(a)

# sorting
c = np.sort(a)
print(c)

# descending order
reverse = np.sort(a)[::-1]
print(reverse)

# append
print(np.append(a,200))

[49 84 65 87 88 78 60 25 84 26  9 22 45 65 70]
[ 9 22 25 26 45 49 60 65 65 70 78 84 84 87 88]
[88 87 84 84 78 70 65 65 60 49 45 26 25 22  9]
[ 49  84  65  87  88  78  60  25  84  26   9  22  45  65  70 200]


In [12]:
# multidimensional
b = np.random.randint(1,100,24).reshape(6,4)
print(b)
# sorting
d = np.sort(b,axis=0)
e = np.sort(b,axis=1)
print(d)
print(e)

# append
np.append(b,np.ones((b.shape[0],1)), axis=1)
#np.append(b,np.random.random((b.shape[0],1)),axis=1)

[[23 90 85 30]
 [42 14 69 64]
 [10 24 56 33]
 [10 43 89 90]
 [13 58 30 41]
 [57 91 54 92]]
[[10 14 30 30]
 [10 24 54 33]
 [13 43 56 41]
 [23 58 69 64]
 [42 90 85 90]
 [57 91 89 92]]
[[23 30 85 90]
 [14 42 64 69]
 [10 24 33 56]
 [10 43 89 90]
 [13 30 41 58]
 [54 57 91 92]]


array([[2.30000000e+01, 9.00000000e+01, 8.50000000e+01, 3.00000000e+01,
        9.57200849e-01],
       [4.20000000e+01, 1.40000000e+01, 6.90000000e+01, 6.40000000e+01,
        9.67799932e-01],
       [1.00000000e+01, 2.40000000e+01, 5.60000000e+01, 3.30000000e+01,
        1.50698641e-02],
       [1.00000000e+01, 4.30000000e+01, 8.90000000e+01, 9.00000000e+01,
        4.25295321e-01],
       [1.30000000e+01, 5.80000000e+01, 3.00000000e+01, 4.10000000e+01,
        5.00193655e-01],
       [5.70000000e+01, 9.10000000e+01, 5.40000000e+01, 9.20000000e+01,
        4.64158966e-01]])

In [16]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

# concatenate
print(c)
print(d)

con = np.concatenate((c,d),axis=1)
print(con)

con1 = np.concatenate((c,d),axis=0)
print(con1)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [17]:
# unique

e = np.array([1,1,2,2,3,3,3,4,4,5,5,6,6])
print(np.unique(e))

[1 2 3 4 5 6]


In [22]:
# expand dimensions

print(a)
print(a.shape)
expanded_a = np.expand_dims(a,axis=0)
print(expanded_a)
print(expanded_a.shape)

expanded_a1 = np.expand_dims(a,axis=1)
print(expanded_a1)
print(expanded_a1.shape)



[49 84 65 87 88 78 60 25 84 26  9 22 45 65 70]
(15,)
[[49 84 65 87 88 78 60 25 84 26  9 22 45 65 70]]
(1, 15)
[[49]
 [84]
 [65]
 [87]
 [88]
 [78]
 [60]
 [25]
 [84]
 [26]
 [ 9]
 [22]
 [45]
 [65]
 [70]]
(15, 1)


In [25]:
# where
print(a)

# returns indices wehre condition is satisfied
wh = np.where(a>50)
print(wh)

[49 84 65 87 88 78 60 25 84 26  9 22 45 65 70]
(array([ 1,  2,  3,  4,  5,  6,  8, 13, 14], dtype=int64),)


In [26]:
# replace all where a > 50

np.where(a>50,0,a)


array([49,  0,  0,  0,  0,  0,  0, 25,  0, 26,  9, 22, 45,  0,  0])

In [27]:
# max element in an array in an axis
print(a)
np.argmax(a)


print(b)
print(np.argmax(b,axis=0))
print(np.argmax(b,axis=1))

[49 84 65 87 88 78 60 25 84 26  9 22 45 65 70]


4

In [32]:
# arg min
np.argmin(a)

print(np.argmin(b,axis=0))


[2 1 4 0]


In [36]:
# cumulative sum
print(a)
print(np.cumsum(a))

print(b)

# if axis not given then converted to 1d
print(np.cumsum(b, axis=0))
print(np.cumsum(b, axis=1))


[49 84 65 87 88 78 60 25 84 26  9 22 45 65 70]
[ 49 133 198 285 373 451 511 536 620 646 655 677 722 787 857]
[[23 90 85 30]
 [42 14 69 64]
 [10 24 56 33]
 [10 43 89 90]
 [13 58 30 41]
 [57 91 54 92]]
[[ 23  90  85  30]
 [ 65 104 154  94]
 [ 75 128 210 127]
 [ 85 171 299 217]
 [ 98 229 329 258]
 [155 320 383 350]]
[[ 23 113 198 228]
 [ 42  56 125 189]
 [ 10  34  90 123]
 [ 10  53 142 232]
 [ 13  71 101 142]
 [ 57 148 202 294]]


In [38]:
# cumulative product

print(np.cumprod(a))
print(np.cumprod(b, axis=0))
print(np.cumprod(b, axis=1))

[         49        4116      267540    23275980  2048286240   852536768
  -387401472 -1095102208 -1794272256   593561600  1047087104  1561079808
  1529114624   608202752  -375480320]
[[         23          90          85          30]
 [        966        1260        5865        1920]
 [       9660       30240      328440       63360]
 [      96600     1300320    29231160     5702400]
 [    1255800    75418560   876934800   233798400]
 [   71580600 -1726845632   109838944    34616320]]
[[      23     2070   175950  5278500]
 [      42      588    40572  2596608]
 [      10      240    13440   443520]
 [      10      430    38270  3444300]
 [      13      754    22620   927420]
 [      57     5187   280098 25769016]]


In [41]:
# percentile

print(a)
# maximum
print(np.percentile(a,100))

# median
print(np.percentile(a,50))

[49 84 65 87 88 78 60 25 84 26  9 22 45 65 70]
88.0
65.0


In [42]:
# histogram (frequency between 0-10, 10-20...)
print(a)
his= np.histogram(a,bins=[1,10,20,30,40,50,60,70,80,90,100])
print(his)

[49 84 65 87 88 78 60 25 84 26  9 22 45 65 70]
(array([1, 0, 3, 0, 2, 0, 3, 2, 4, 0], dtype=int64), array([  1,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


In [43]:
# corelation coefficient
# returns pearson product-moment correlation coefficient
# coef is b/w -1 and 1
# relation between two variables
sal = np.array([20000,40000, 25000, 35000, 60000])
exp = np.array([1,3,2,4,2])


np.corrcoef(sal,exp)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [46]:
# is in
print(a)
items = [10,20,30,40,50,60,70,80,90,100]
inside = np.isin(a,items)
print(inside)

[49 84 65 87 88 78 60 25 84 26  9 22 45 65 70]
[False False False False False False  True False False False False False
 False False  True]


In [49]:
# flip reverses order along any specified axis
# not useful
print(a)
print(np.flip(a))

print(b)
print(np.flip(b))
print(np.flip(b, axis=0))
print(np.flip(b, axis=1))


[49 84 65 87 88 78 60 25 84 26  9 22 45 65 70]
[70 65 45 22  9 26 84 25 60 78 88 87 65 84 49]
[[23 90 85 30]
 [42 14 69 64]
 [10 24 56 33]
 [10 43 89 90]
 [13 58 30 41]
 [57 91 54 92]]
[[92 54 91 57]
 [41 30 58 13]
 [90 89 43 10]
 [33 56 24 10]
 [64 69 14 42]
 [30 85 90 23]]
[[57 91 54 92]
 [13 58 30 41]
 [10 43 89 90]
 [10 24 56 33]
 [42 14 69 64]
 [23 90 85 30]]
[[30 85 90 23]
 [64 69 14 42]
 [33 56 24 10]
 [90 89 43 10]
 [41 30 58 13]
 [92 54 91 57]]


In [51]:
# put replaces specific elem with given values
# changes in original array
print(a)
np.put(a,[0,1], [333,666])

print(a)

[49 84 65 87 88 78 60 25 84 26  9 22 45 65 70]
[333 666  65  87  88  78  60  25  84  26   9  22  45  65  70]


In [58]:
# delete
print(a)
a = np.delete(a,[0, 2, 4])
print(a)

[333 666  65  87  88  78  60  25  84  26   9  22  45  65  70]
[666  87  78  60  25  84  26   9  22  45  65  70]


In [63]:
# set functions

m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)
np.intersect1d(m,n)
# in m but not in n
np.setdiff1d(m,n)

np.setxor1d(m,n)

# whether elem is in set
np.in1d(m,1)
# returns elem
m[np.in1d(m,1)]



array([1])

In [64]:
# clip
print(a)
np.clip(a,a_min=25,a_max=75)

[666  87  78  60  25  84  26   9  22  45  65  70]


array([75, 75, 75, 60, 25, 75, 26, 25, 25, 45, 65, 70])