In [16]:
import numpy as np
import matplotlib.pyplot as plt

a = np.arange(12).reshape(4,3)
print(a)

#fancy indexing
print(a[[0,2,3]])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
#boolean indexing
b = np.random.randint(0,100,24).reshape(6,4)
print(b)
print(b[b>50])
print(b[b%2==0])


[[37 31 87  0]
 [88 78  2 61]
 [93 89 25 87]
 [39 19 91 63]
 [94 65 39  3]
 [96 88 62 23]]
[87 88 78 61 93 89 87 91 63 94 65 96 88 62]
[ 0 88 78  2 94 96 88 62]


In [7]:
# broadcasting
# smaller array is broadcasted across larger array so that they have compatible shapes

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)
print(a+b)


[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [8]:
a = np.arange(10)
b = np.sum(a)


# sigmoid
def sigmoid(array):
    return 1/(1+np.exp(-array))

sigmoid(a)

# mean squared error


# categorical cross entropy

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [13]:
# working with missing values
 
c = np.array([1,2,3,4,5,np.nan,6])

print(np.isnan(c))
print(c[np.isnan(c)])
print(c[~np.isnan(c)])

[False False False False False  True False]
[nan]
[1. 2. 3. 4. 5. 6.]


In [19]:
# plotting a 2d plot
x = np.linspace(-10,10,100)
# y = x
y = x *log x

plt.plot()

SyntaxError: invalid syntax (3388882105.py, line 4)